### ISSUE TITLE
How to get offset

### ISSUE THREAD

**Issue by nerdunit** [korcankaraokcu/PINCE#115]
Hi, could someone write a short tutorial on how to get offsets?
I have a program that just makes an int variable and shows me its address vale and allows me to modify it, I want to try to modify it from an external program but the address changes each start, how could I get the offsets so I have the address without the first program showing it to me each time?

**Comment by Gregaras** [comment]
I'm not sure If this might work, but I guess you could try to go to Memory Regions window which you can access from the Memory Viewer > View > Memory Regions, look for your program and see in which addresses it is located. Then I guess you would just subtract the int value address from the beginning address of the program to get the offset.

**Comment by korcankaraokcu** [comment]
You should find the static addresses that the values are linked to. You might want to disable ASLR beforehand. The techniques shown in Cheat Engine tutorials can be mostly applied within PINCE as well. You'll have to google the details by yourself since PINCE doesn't have an embedded tutorial yet, good luck
