### ISSUE TITLE
Flatpak builds

### ISSUE THREAD

**Issue by jcc10** [korcankaraokcu/PINCE#141]
It would be really useful to have flatpak builds of the app.

The main reason I would appreciate it is that the steam deck only officially supports flatpak installs.

**Comment by korcankaraokcu** [comment]
This has been requested in the discord chat as well, I'll eventually create it. Keeping this issue open till then, any help is welcome

**Comment by TheDragonkeeper** [comment]
I second this.
Or maybe just a an AppImage would be useful.

The compiling/setup on the steam deck is quite problematic and has to be done on every system update due to the nature of its immutable filesystem.

If a distribution method can be looked at next it would be much appreciated

**Comment by raspin0** [comment]
Trying to install on deepin and Dealing with dependency issues are killing me.. I believe appimages will be first to die out. Flatpak is default on steamdeck and this should keep app up-to-date.

**Comment by TheDragonkeeper** [comment]
> This has been requested in the discord chat as well, I'll eventually create it. 

This has been open a year now. Any idea if 'eventually' will be in the foreseeable future?

**Comment by korcankaraokcu** [comment]
> Any idea if 'eventually' will be in the foreseeable future?

Idk, I'm currently dealing with more critical issues and core features. I haven't done anything regarding flatpak. Pull requests are always welcome, especially in this case since I don't have any experience with flatpak

**Comment by brkzlr** [comment]
To complete what Korcan said, we already had some work in progress for creating an AppImage of PINCE, but we ran into some issues which were hard to fix at the time.

Given the many changes to the underlying system that have been done since then, we'll try to give it a try again in the near future, but we can't make promises as we have other more critical issues right now and it depends on our free time.

Btw we have a slight preference towards AppImage instead of Flatpak due to the sandboxing that Flatpak is designed for. This can cause issues with trying to access other applications memory which is what PINCE is designed for. AppImage makes sandboxing optional instead of required like Flatpak AFAIK so it wouldn't cause memory access issues.

**Comment by TheDragonkeeper** [comment]
Okay i didnt realise that about flatpak, i was under the impression everything was under a set permission so processes would just need /proc access .

An appimage would be a welcome addition as well, ive pretty much given up trying to use PINCE on systems where this is needed due to the install process.

**Comment by brkzlr** [comment]
I'm not very knowledgeable on Flatpak so this might be some outdated info as well and there might be a way to have it access other apps, but AFAIK AppImage is also runnable on every Linux distribution we officially support out of the box, without the need to install something to make it run.

Ubuntu still cannot run Flatpak out of the box IIRC so there are other smaller reasons for why we prioritize AppImage over Flatpak, but this doesn't mean we wouldn't also support it in the future when we make it self-contained. It's just a matter of order for supporting possibly both.

**Comment by korcankaraokcu** [comment]
AppImage packaging has been implemented, closing this issue
