### ISSUE TITLE
float parse failure

### ISSUE THREAD

**Issue by HookedBehemoth** [korcankaraokcu/PINCE#151]
Trying to search for floats does nothing. In the terminal I get: 
```
error: unable to parse number `0,42`
```
Even though I entered `0.42`. Using a comma has the same result.
I assume this is some locale issue. Here's mine, which is the same for root.
```
$ locale -a
C
C.UTF-8
en_US.utf8
POSIX
```
I see you automatically convert dots to commas. Could your user local be different from root.
Launching by passing my environment variables causes it to get stuck as it tries to access the users run directory.
```
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
/home/behemoth/source/PINCE/PINCE.py:5613: Warning: cannot register existing type 'GtkWidget'
  app = QApplication(sys.argv)
/home/behemoth/source/PINCE/PINCE.py:5613: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  app = QApplication(sys.argv)
/home/behemoth/source/PINCE/PINCE.py:5613: Warning: cannot register existing type 'GtkBuildable'
  app = QApplication(sys.argv)
/home/behemoth/source/PINCE/PINCE.py:5613: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  app = QApplication(sys.argv)
/home/behemoth/source/PINCE/PINCE.py:5613: Warning: g_once_init_leave: assertion 'result != 0' failed
  app = QApplication(sys.argv)
/home/behemoth/source/PINCE/PINCE.py:5613: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  app = QApplication(sys.argv)
  ```

**Comment by korcankaraokcu** [comment]
That's interesting, I don't have any issues with my locale as well. I also cannot reproduce this on my machine. PINCE uses scanmem in the background to search memory. Try using [scanmem](https://github.com/scanmem/scanmem) to search for floats and tell me if you encounter any issues.

**Comment by jaredballou** [comment]
There is some logic in the PINCE.py file in lines 1067-1068 to account for the fact that GDB uses the dot "." as a decimal separator instead of European style comma "," - and to make things harder, GDB returns tokenized values delimited by the comma. This logic has also caused me a similar issue in the past.

**Comment by korcankaraokcu** [comment]
```python
search_for = search_for.replace(".", ",")
```
That piece of code is used to validate input for scanmem, not GDB. I'm aware of the conversion logic but it's weird that I cannot reproduce while having no locale issues on my end

**Comment by MayeulC** [comment]
Locale handling is inconsistent.

```
% locale -a
C
C.UTF-8
en_US.utf8
fr_FR.utf8
POSIX
```

In the main value input window, I must enter commas (`LC_NUMERIC=fr_FR.utf8` expects it that way). In the variable editor, it seems like entering dots work.
Using the numpad produces a dot, which is not accepted in the input window.

I would probably define a specific type for strings input by the user, and normalize them before passing them on. This would also allow using spaces or other separators (no comma, that would be dangerous) to group digits, for instance. Or allow calculation/suffixes at a later date.

As a side note, instead of rejecting dots/commas, it would be nice to switch the input to the correct type instead.

**Comment by korcankaraokcu** [comment]
https://github.com/korcankaraokcu/PINCE/commit/18461fb08e1002e7d7367af153562c2b2972a4fa fixes this issue. Sorry for taking long, completely forgot about this one
