### ISSUE TITLE
Current user in install script is empty?

### ISSUE THREAD

**Issue by salihmarangoz** [korcankaraokcu/PINCE#189]
Tried the install script but `CURRENT_USER` variable seems empty. Is this intentional?

```bash
CURRENT_USER="$(who mom likes | awk '{print $1}')"
echo $CURRENT_USER
exit
```

I think `whoami` would be better command here.

**Comment by brkzlr** [comment]
It's not intentional. Looks like the common "who am i" or "who mom likes" commands are returning empty for some terminals. On our tested terminals it works correctly.

Might be a problem as some terminals do not correctly return some info needed by who when the 2 random arguments are supplied (effectively converting it to `who -m`).

@korcankaraokcu We can just remove the "mom likes" easter egg (sadly) and that should fix it for all terminals.

**Comment by salihmarangoz** [comment]
I am using GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu). Also, I wouldn't recommend using `who` to detect the current user. For example, I have a multi-head system where two people are using the same system but the output of  `who` is the same for both users. In this case, the first line doesn't represent the current user, because when `user2` run `who` command the output will look like this:

```
user1    :2           2023-06-03 02:34 (:2)
user2    :0           2023-06-03 02:34 (:0)
```

Alternatively using `id -un` may be better... Maybe...

```bash
CURRENT_USER="$(whoami)"
# or...
CURRENT_USER="$(id -un)"
```

**Comment by brkzlr** [comment]
'who' was most likely chosen because 'whoami' is affected by sudo and other effective user id changing tools, which would mess up the permissions set by the script.

I guess we can change now to 'whoami' since we recently introduced safeguards against sudo running.

**Comment by korcankaraokcu** [comment]
There goes another easter egg...

`whoami` is included in coreutils, it's a good replacement
