### ISSUE TITLE
Issues with decreasing search after unknown search

### ISSUE THREAD

**Issue by korcankaraokcu** [korcankaraokcu/PINCE#226]
Steps to reproduce:
1) Scan type "unknown value" / Int(any)
2) Start first scan
3) Second scan with scan type "decreased" => ok
4) Third scan with scan type "decreased" => ok
5) Repeat as many as needed
6) At some point, "unknown" types will be present in the search table

This "unknown" type used to crash PINCE. To avoid this, it has been ignored for now with https://github.com/korcankaraokcu/PINCE/commit/7640b2e7d94ca92c2cfb9ba84e69ef2b04486dc5
Also, it's impossible to undo after decreased search

**Comment by brkzlr** [comment]
Undo being broken after decreased actually happens with every type of operator search (Increased/Decreased etc).

This has been fixed in https://github.com/brkzlr/libscanmem-PINCE/commit/6a9cf777ed764feef9e959251e61d9281964713f

I'll check the unknown issue and create a PR for both of these once it's fixed.

**Comment by brkzlr** [comment]
PR to fix the undo issues is up: https://github.com/korcankaraokcu/PINCE/pull/227

As discussed privately, the unknown type issue cannot really be resolved as it's just scanmem parsing logic which tries to fit a type to every possible memory combination, which most of the time it's not possible.

Ignoring it like GameConqueror does is the best solution right now and I'm pretty sure that all of the unknown values are not usable values by the user in a real-life scenario as well.

We can revisit this issue if an important value is ignored because of unknown shenanigans.

**Comment by korcankaraokcu** [comment]
Fixed by #227
