### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Tybobobo** [korcankaraokcu/PINCE#24]
Running Linux Mint 18.1
No problems during installation (using install.sh), and I had to install the extra since to be able to select processes.

**Screenshot with the error:**
https://i.imgur.com/cxkxFDI.png

I would be more to happy to provide additional details wherever possible. I suspect something went bad with the compilation process. Perhaps some changes have been made without testing on Linux Mint? Hopefully not that serious. :)

**Comment by korcankaraokcu** [comment]
As it writes in the features part of the readme, memory searching feature isn't implemented yet. So that button is there to test an exception for now. I'll first implement the debugger based features, then the memory searching features because there are already memory searching tools such as GameConqueror and you can use stuff like GC with PINCE by detaching PINCE from GDB Console for now.

To do this, open GDB Console from top right. Execute the command "phase-out". Search memory with GC. When you are done with GC, execute the command "phase-in" to attach PINCE back to the process. Finally, copy the results from GC to PINCE and have fun with debugging features.

There are really useful debugging features such as tracing, .so file injection, internal calling, what writes to this address etc.

Any other questions?

**Comment by Tybobobo** [comment]
Ah I see. Features that are not implemented should definitely be more clear. 
Disabling those buttons would go a long way. :)

**Comment by korcankaraokcu** [comment]
Sorry for the delay, forgot to write here. PINCE now displays some information about this topic when you click First Scan. I thought it was clear enough since it's written at the beginning of the Features part of the readme, looks like I was wrong.

Thanks for the report, have a good day.
