### ISSUE TITLE
Problem with scan in "unknown value" mode

### ISSUE THREAD

**Issue by X-Keyscore** [korcankaraokcu/PINCE#256]
When I am specifically in this mode, the search launches then the  `PINCE.sh` console indicates `killed` after that the program exits and the target remains open and usable. I was told in another issue that it was the target that was preventing debugging but I'm not sure that's what's happening here.

Didn't see any gdb error. Probably because it is not affected by this action but I admit that I have difficulty understanding how the pince works.

When I use the `exact` mode everything goes well.

(sorry for the spam but I can't find any info elsewhere)

**Comment by Bloodiko** [comment]
"Killed" means, your process, in this case the scanmem sub-process of pince, got killed due to the system beeing oom, which will trigger a system response by killing the process. 
Try searching something less broad, for example you could use "in between" which does result in far less results. 
Also, if possible, keep it above or below 0 if possible, because on large processes, 0 will produce massive amounts of results potentially, which are most likely useless. 

But the memory issue is definitely something we might need to address at some point.

**Comment by X-Keyscore** [comment]
ok thank you for the response, I have already tried between but I did not think that 0 was spread in the memory which seems logical.
