### ISSUE TITLE
Absolute gdb path by default is unnecessary

### ISSUE THREAD

**Issue by xunuwu** [korcankaraokcu/PINCE#262]
There's no reason to have the default gdb path set to an absolute path (/bin/gdb).
From what I've found the only use of the gdb path setting is in [libpince/debugcore.py](https://github.com/korcankaraokcu/PINCE/blob/823b213c531d9ffda1aa2b6504bc8a9eefc0c27f/libpince/debugcore.py#L526).

pexpect.spawn does not need an absolute path, "[Note that spawn is clever about finding commands on your path. It uses the same logic that “which” uses to find executables.](https://pexpect.readthedocs.io/en/stable/api/pexpect.html)".

I have tried changing the value in the settings to be just "gdb" and it works fine. Unless I am missing something having the path be absolute be default only limits compatibility for no real reason.

**Comment by brkzlr** [comment]
If you're using our AppImage builds (which every user should), that setting is completely ignored since we're hardlinking in code to our bundled gdb. So no matter what you type in there, it will be ignored.

I forgot to gray out that setting after introducing the builds so that might contribute to the confusion as well, but this will be fixed very soon, so sorry for that.

About the path, I'm not entirely sure but I think it was that way to avoid potential sudo user environment variables changing which gdb we're using so an absolute path was used, but since then `-E` and other options were introduced which could allow the "which"-like functionality to work.
At the same time, all of our supported distros for the local dev builds have gdb in that path so it doesn't "limit compatibility for no real reason".

What do you think @korcankaraokcu?

**Comment by korcankaraokcu** [comment]
> I forgot to gray out that setting after introducing the builds so that might contribute to the confusion as well, but this will be fixed very soon, so sorry for that

Done with https://github.com/korcankaraokcu/PINCE/commit/d98701d89243fcf070ee33b6f851a8e7c3200639

All of the supported local dev distros use that static path and that path isn't even used in AppImage builds. So this change is kinda unnecessary. Will be closing this one since no action is needed for now. Have a good day!
