### ISSUE TITLE
How to change PINCE_USER_FILES location?

### ISSUE THREAD

**Issue by Winterwolf** [korcankaraokcu/PINCE#33]
My home location is not for randomly generated trash! :( This looks pretty ugly:

![screenshot](https://user-images.githubusercontent.com/405685/31865021-7ec12cd2-b770-11e7-95fd-65d5df8ae26a.png)

**Comment by TsarFox** [comment]
This fix is probably going to take some time, since I'm going to need to consult with the maintainer about a few things. For now, here's a temporary workaround:
```
PINCE_USER_FILES="/var/pince" && sed -i "s~ROOT_PATH =.*~ROOT_PATH = \"$PINCE_USER_FILES\" + \"/PINCE_USER_FILES/\"~" libPINCE/type_defs.py
```
Run it from the root of the source tree, and edit PINCE_USER_FILES to the path you want to use. In that example, it will start using "/var/pince/PINCE_USER_FILES" as the path.

**Comment by Winterwolf** [comment]
Thanks!

**Comment by korcankaraokcu** [comment]
@Winterwolf No more need of that workaround. PINCE config files now reside in `~/.config/PINCE` with [this](https://github.com/korcankaraokcu/PINCE/commit/0e128f0e1ed035206327efb260c95c0427b49113) commit

**Comment by korcankaraokcu** [comment]
@Winterwolf Could you please check your PINCE.conf file and tell its location? It should be either in /root/.config/PINCE or ~/.config/PINCE

**Comment by korcankaraokcu** [comment]
With the latest patches, we've completely fixed this problem along with the bug that causes PINCE.conf being created in `/root` directory in many operating systems(including Archlinux). Please reopen this issue if you encounter this problem again. Have a good day.
