### ISSUE TITLE
Memory Scan

### ISSUE THREAD

**Issue by AshFTW** [korcankaraokcu/PINCE#34]
Why I should use console to attach/detach GDB?

**Comment by korcankaraokcu** [comment]
Because a process can only be debugged/ptrace'd by one process at a time and both scanmem and PINCE(gdb) uses ptrace to access tracee's memory. So, you'll need to detach PINCE temporarily in order to use scanmem or vice versa. Any questions?

**Comment by AshFTW** [comment]
I mean that it is enhancement. Anyway why you cant implement this at least as hotkey?

**Comment by korcankaraokcu** [comment]
Oh, ok then. I'll implement a toggle hotkey for attaching/detaching. Which key would you prefer it to be?

**Comment by AshFTW** [comment]
<kbd>F4</kbd> will be perfect

**Comment by korcankaraokcu** [comment]
Makes sense, since <kbd>F1</kbd>, <kbd>F2</kbd> and <kbd>F3</kbd> shortcuts are process status related. But aren't they a bit too close to each other? You could press <kbd>F4</kbd> while trying to press <kbd>F3</kbd> or <kbd>F5</kbd>. How about using a key modifier, like <kbd>Shift</kbd>+<kbd>F4</kbd>, <kbd>Ctrl</kbd>+<kbd>F4</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd>?

This is just a suggestion tho, I can still set it as <kbd>F4</kbd> if you think that you won't press it by accident

**Comment by korcankaraokcu** [comment]
Just noticed that <kbd>F4</kbd> is already being used as `shortcut_set_address` in `MemoryViewerWindow` so I can't really set it as hotkey for attaching/detaching. You'll have to settle for <kbd>Shift/Ctrl/Alt</kbd>+<kbd>F4</kbd> or a distant F button like <kbd>F10</kbd>. My vote is for <kbd>F10</kbd> btw, since it's less confusing.

**Comment by polarathene** [comment]
`F10` sounds good :)

**Comment by korcankaraokcu** [comment]
Completely forgot about this issue, sorry about that. <kbd>F10</kbd> it is then! Working on the patch right now.

**Comment by korcankaraokcu** [comment]
It's done! Update PINCE by executing `git pull` and enjoy the new features:

Added <kbd>F10</kbd> global shortcut to toggle between attach and deatch
Toggle attach shortcut can be changed from Settings
Toggling between attach and detach modes informs the user about the new state of the process
Reworked the codebase for global shortcut settings. Adding new shortcuts to PINCE is even easier now
Updated the [Using GameConqueror with PINCE](https://github.com/korcankaraokcu/PINCE/wiki/Using-GameConqueror-with-PINCE) wiki page

@polarathene @AshFTW Please test the new features and lemme know if they work properly for you

**Comment by polarathene** [comment]
@korcankaraokcu I don't have time to test much, I updated and can confirm that F10 hotkey works a treat with correct dialog prompt notification each time. Thanks :)

**Comment by korcankaraokcu** [comment]
Thanks for the confirmation, glad that it works properly for you. I'm going to close this issue for now. Reopen if you encounter problems related to this problem. Have a good day!

**Comment by korcankaraokcu** [comment]
This hotkey now has a shift modifier, so it's <kbd>Shift+F10</kbd> instead of just <kbd>F10</kbd>. Updated the [Using GameConqueror with PINCE](https://github.com/korcankaraokcu/PINCE/wiki/Using-GameConqueror-with-PINCE) wiki page as well
